version: "{build}"
build: off
platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: if ($env:nodejs_version -eq "5") { npm i npm@latest -g }
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm install --msvs_version=2013

test_script:
  - npm test
